# next ID is 10
# skipped 01, 0e

# today
["0 0 3 * * * *"]
0a = "[today] practice swordcraft"
0f = "[today] advance alchemic knowledge"

# sunday
["0 0 3 * * Sun *"]
00 = "[duty] journal tribe movements"
06 = "clean the dungeon"

# lamps
["0 0 3 3,18 * * *"]
02 = "[!] change oil in lamps"

# month
["0 0 3 1 * * *"]
04 = "send anonymous prank letters to the King"
05 = "clean the staples"
0b = "hunt"
0d = "wash my pants"

# monthly_not_winter
["0 0 3 1 Apr-Oct * *"]
03 = "[!] feed the platypus bear"

# seasonal
["0 0 3 15 Dec,Mar,Jun,Sep * *"]
07 = "sell toenails"
08 = "buy sausages (1000 lb)"
0c = "buy ritual paint (3), rags (3)"
09 = "[duty] fight hornets"
